### ISSUE TITLE
Dependencies and perspective

### ISSUE THREAD

**Issue by hueper** [pinecreativelabs/Brutalist-Framework#2]
Hi @pinecreativelabs ,
I really like the idea of building a brutalist framework. However I’m not sure if depending on jQuery or other libraries will meet the spirit of brutalism.

> 1. Formal legibility of plan
> 2. clear exhibition of structure, and 
> 3. valuation of materials for their inherent qualities 'as found'.

from _[1955 December: 'The New Brutalism' by Reyner Banham](https://artearquiteturadesign2.files.wordpress.com/2014/10/1955-december_-the-new-brutalism-by-reyner-banham-_-archive-_-architectural-review.pdf)_
 
You write on your website: "Brutalist web design is the anti-conventional approach to proper, modern web design principles. In essence, it harkens back to the days of a more primitive web". I like that idea, but for me this would also mean, one had to stick to the very basics when building a brutalist framework. Less fancy javascript libraries, more raw material.

What do you think? Would be great to read more about your plans in a README.

Best,
Moritz

**Comment by hueper** [comment]
If you want to get rid of jQuery, you can:
https://github.com/HubSpot/YouMightNotNeedjQuery

**Comment by rainwoodman** [comment]
@hueper  Could you elaborate a bit more on the three conditions? How do they map into concepts of web interface?

Form and functionality are already quite unified in terms of UI widgets. 

My gut feeling is that Brutalism shall be different from a revival of 90 style. Using large blocks of flashy colors is not really aligned with the core of Brutalism.
